version: '3.8'

services:
  db:
    image: postgres:14
    container_name: agente-backend-db
    restart: always
    environment:
      POSTGRES_USER: adminagent
      POSTGRES_PASSWORD: Jb3IFxYzHcarFqXv
      POSTGRES_DB: agente_backend_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agente-backend
    restart: always
    # Remova ou comente a linha abaixo se não precisar mais do arquivo .env
    # env_file:
    #   - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://adminagent:Jb3IFxYzHcarFqXv@db:5432/agente_backend_db"
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  #prospection:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.prospection
  #  container_name: agente-backend-prospection
  #  restart: always
  #  env_file:
  #    - .env
  #  depends_on:
  #    - db
  #    - backend
  #  environment:
  #    DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

volumes:
  db_data: