FROM python:3.10-slim

WORKDIR /app

# Instalar dependências do sistema necessárias para WeasyPrint e psycopg2
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libgdk-pixbuf2.0-0 \
    libgdk-pixbuf2.0-dev \
    libffi-dev \
    libpango1.0-0 \
    libcairo2 \
    libcairo2-dev \
    libgirepository1.0-dev \
    libpangocairo-1.0-0 \
    fonts-liberation \
    libxml2 \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar e instalar dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o script de espera e torná-lo executável
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh

# Copiar o código do projeto
COPY . .

# Definir PYTHONPATH
ENV PYTHONPATH=/app

# Comando para aguardar o banco de dados e iniciar o backend
#CMD ["sh", "-c", "./wait-for-it.sh db:5432 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
CMD ["sh", "-c", "./wait-for-it.sh db:5432 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips '127.0.0.1'"]
